version: "3.9"
services:
  dr_stonks:
    container_name: dr_stonks
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BLUESKY_USERNAME: ${BLUESKY_USERNAME}
      BLUESKY_PASSWORD: ${BLUESKY_PASSWORD}
    volumes:
      - .:/code
    command: python3 main.py


networks:
  default:
    driver: bridge
