name: Dr. Stonks

on:
  schedule:
    - cron: "0 22 * * 1-5"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Debug Environment Variables
        run: |
          echo "BLUESKY_USERNAME is set"
          echo ${{ secrets.BLUESKY_USERNAME }}
          echo "BLUESKY_PASSWORD is set"
          echo ${{ secrets.BLUESKY_PASSWORD }}
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

